In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [14]:
import numpy as np

# a = [1 , 2 ,3]
a = np.array([
    [1,2,3],
    [4,5,6]
])
print (a)
print (type(a)) 
# nu merge daca am alte tipuri
# b = np.array([1,"fa",3], dtype=np.int8)
# print (b)

print(a.shape) # avem 2 linii si 3 coloane
# in numpy vom avea arrayuri multidimensionale
print(a.size) # avem 6 elemente


np.zeros((2,3), dtype=np.int8) # matrice de 0
np.ones((2,3), dtype=np.int8) # matrice de 1
np.full((2,3), 5, dtype=np.int8) # matrice de 5
np.eye(3) # matrice identitate
np.random.random((2,3)) # matrice random intre 0 si 1 uniforma
np.random.random((2,3)) * 2 - 1 # matrice random intre -1 si 1


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
6


array([[ 0.31641394, -0.86679358, -0.24205919],
       [-0.43233041, -0.23951061, -0.09805671]])

In [18]:
list(range(10)) # range(0,10)
# echivalent in numpy
np.arange(2,10,2)


array([2, 4, 6, 8])

In [19]:
a = np.arange(6)
b = np.random.random(6)
print(a)
print(b)

[0 1 2 3 4 5]
[0.7760434  0.05159364 0.49706766 0.98728454 0.94364521 0.08677002]


In [27]:
a + b
a - b
a * b
a ** b
print(a)
a.min()
a.max()
print(a.mean())
print(np.mean(a))

[0 1 2 3 4 5]
2.5
2.5


In [29]:
# definim o matrice
a = np.array([
    [1,2,3],
    [4,5,6]
])
a = np.array(a)
print(a.dtype)


int64


In [35]:
# putem defini mai interesant ce este minim
a.min(axis=0) # face minim la nivelul liniilor,se uita pe fiecare elemnt dintre fiecare linie si ia minimul

array([1, 2, 3])

In [37]:
c = [1,2,3,4]
print(c[1:3])

[2, 3]


In [72]:
a = [
    [1,2,3],
    [4,5,6]
]
a[0:2,1]


TypeError: list indices must be integers or slices, not tuple

In [58]:
a = [
    [1,2,3],
    [4,5,6]
]
a = np.array(a)
a[0:2,1] # in numpy putem indexa mult mai easy
a[1,1]

a.transpose() 
a.T

np.int64(5)

In [71]:
print("a" , a)
print("a shape" ,a.shape)
b = np.array([2,3,2])
b = b.reshape(3,1) # imi transforma matrice in 3 linii cu cate o coloana
print("b reshape" ,b)
# print(b)
# a + b 
print("b shape",b.shape) # nr linii coloane.
# dotul cel mai folosit pt imultire
# a.dot(b)
a @ b
np.matmul(a,b)

a [[1 2 3]
 [4 5 6]]
a shape (2, 3)
b reshape [[2]
 [3]
 [2]]
b shape (3, 1)


array([[14],
       [35]])