In [5]:
import torch
import numpy as np



In [3]:
%pip install timed-decorator

^C
Note: you may need to restart the kernel to use updated packages.


In [ ]:
from timed_decorator.simple_timed import timed

Tensor

Tensor Creation

In [6]:
# From Python lists:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [7]:
# Random tensor with a given size
torch.rand((4, 8))

tensor([[0.5653, 0.0145, 0.1358, 0.1695, 0.3517, 0.9597, 0.3191, 0.6854],
        [0.2957, 0.7284, 0.2175, 0.4252, 0.2759, 0.4144, 0.0937, 0.4249],
        [0.7365, 0.3160, 0.1749, 0.6149, 0.4166, 0.5605, 0.6969, 0.3467],
        [0.3892, 0.2556, 0.8766, 0.4001, 0.6216, 0.6341, 0.5263, 0.5044]])

In [8]:
# Zero tensor
torch.zeros((3, 3, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [9]:
torch.arange(5, 15, 2)

tensor([ 5,  7,  9, 11, 13])

In [10]:
torch.full((2, 10), 5)

tensor([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [11]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [12]:
torch.linspace(0, 10, 5)    

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [13]:
torch.logspace(0, 10, 5)

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10])

In [14]:
torch.ones((3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch.randperm(10)

tensor([5, 9, 3, 4, 7, 0, 1, 2, 8, 6])

In [20]:
t1 = torch.rand((100, 20, 30))
t2 = torch.rand((100, 20, 30))
print(t1.shape, t2.shape)

torch.Size([100, 20, 30]) torch.Size([100, 20, 30])


In [21]:
print((t1 * t2).shape)
torch.equal(t1 * t2, torch.mul(t1, t2))

torch.Size([100, 20, 30])


True

In [22]:
import torch

v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])

# Dot product
dot_product = torch.dot(v1, v2)
print(dot_product)  # tensor(32)

tensor(32)


In [23]:
t2t = t2.transpose(1, 2)
print(t2t.shape)
print((t1 @ t2t).shape)

torch.Size([100, 30, 20])
torch.Size([100, 20, 20])


In [26]:
print(torch.bmm(t1, t2t))
torch.equal(t1 @ t2t, torch.bmm(t1, t2t))

tensor([[[ 7.9413,  7.8629,  7.5608,  ...,  7.7986,  7.6449,  5.8026],
         [10.2346,  8.7134,  8.7386,  ...,  9.9835,  8.6866,  6.1349],
         [ 6.8187,  7.0815,  6.3547,  ...,  7.4693,  7.1101,  4.9660],
         ...,
         [ 8.0686,  8.5164,  6.6993,  ...,  7.3272,  7.6603,  5.6119],
         [ 8.6176,  6.9113,  7.4934,  ...,  8.0423,  7.7091,  5.0782],
         [11.1070,  8.7463,  8.5695,  ...,  9.5451,  8.9064,  6.3529]],

        [[ 8.8496,  8.8087,  7.5778,  ...,  7.9882,  6.5325,  7.5678],
         [ 9.3851,  7.9157,  7.5244,  ...,  7.1829,  6.5684,  7.6917],
         [ 7.6713,  7.2329,  7.0724,  ...,  6.6935,  6.4238,  6.7644],
         ...,
         [ 9.0739,  7.3360,  7.6733,  ...,  6.8926,  6.3890,  7.3290],
         [ 8.6224,  7.6174,  8.7040,  ...,  7.4443,  6.0331,  7.7325],
         [ 9.7500,  8.6522,  9.2833,  ...,  7.9703,  7.2328,  8.1322]],

        [[ 9.9556,  6.6036,  7.0782,  ...,  8.1292,  9.3431,  6.3083],
         [ 9.5323,  7.2920,  7.9704,  ...,  8

True

In [27]:
torch.equal(t1 @ t2t, torch.matmul(t1, t2t))

True

In [37]:
torch.equal(t1 * t2, torch.mul(t1, t2))
print(torch.mul(t1,t2).shape)
print(torch.matmul(t1,t2t).shape)


torch.Size([100, 20, 30])
torch.Size([100, 20, 20])


In [38]:
t2t = t2.transpose(1, 2)
print(t2t.shape)
print((t1 @ t2t).shape)

torch.Size([100, 30, 20])
torch.Size([100, 20, 20])


In [39]:
torch.equal(t1 @ t2t, torch.bmm(t1, t2t))

True

In [40]:
torch.equal(t1 @ t2t, torch.matmul(t1, t2t))

True

In [42]:
import torch
print(torch.cuda.is_available())  # Pentru Nvidia
print(torch.backends.mps.is_available())  # Pentru Apple Silicon (dacă ai Mac)
print(torch.backends.mps.is_built())  # Dacă ROCm este disponibil pentru AMD


False
False
False
