In [ ]:
import torch

# Crearea unui tensor 2D de exemplu
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6],[4, 5, 6]])

# Aplatizarea tensorului
flattened_tensor = torch.flatten(tensor_2d)

print("Tensor original:\n", tensor_2d)
print("Tensor aplatizat:\n", flattened_tensor)

In [4]:
import torch

# Create a 3D tensor
tensor_3d = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])

# Flatten the tensor into a single vector
flattened_tensor = torch.flatten(tensor_3d)
view_torch = tensor_3d.view(-1,4)
print("Original tensor:\n", tensor_3d)
print("Flattened tensor:\n", flattened_tensor)
print("View tensor:\n", view_torch)


Original tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Flattened tensor:
 tensor([1, 2, 3, 4, 5, 6, 7, 8])
View tensor:
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
import torch

# Create a tensor with a dimension of size 1
tensor_with_ones = torch.tensor([[[1, 2, 3]]])

# Squeeze the tensor to remove dimensions of size 1
squeezed_tensor = torch.squeeze(tensor_with_ones)

print("Original tensor:\n", tensor_with_ones)
print("Squeezed tensor:\n", squeezed_tensor)

In [15]:
import torch

# Create a 2D tensor
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])

print (tensor_2d.view(-1,1,2))

# Reshape the tensor to a different shape
reshaped_tensor = tensor_2d.view(3, 2)

print("Original tensor:\n", tensor_2d)
print("Reshaped tensor:\n", reshaped_tensor)

tensor([[[1, 2]],

        [[3, 4]],

        [[5, 6]]])
torch.Size([2, 3])
Original tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Reshaped tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:

t1 = torch.ones(2,2,3)
t2 = torch.zeros(3,3)
t3 = torch.rand(3,3)
t4 = torch.randn(3,3)


In [ ]:
%pip install jupyter_contrib_nbextensions
%jupyter contrib nbextension install --user


In [3]:
import torch
t3 = torch.tensor([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])
t3.max(dim=0)

torch.return_types.max(
values=tensor([21, 22, 23, 24, 25]),
indices=tensor([4, 4, 4, 4, 4]))