In [7]:
import pickle

# Load the model parameters from a file
# Load the model parameters from a file
with open("model_parameters_before_dropout.pkl", "rb") as file:
    model_parameters = pickle.load(file)

# Extract the model parametersZ
w1 = model_parameters["w1"]
b1 = model_parameters["b1"]
w2 = model_parameters["w2"]
b2 = model_parameters["b2"]

print(w1.shape)
print(b1.shape)
print(w2.shape)
print(b2.shape)

(784, 100)
(1, 100)
(100, 10)
(1, 10)


In [17]:
def dropout_function(layer_output, dropout_rate):
    # Generate a mask that will zero out neurons with probability dropout_rate
    mask = (np.random.rand(*layer_output.shape) < (1- dropout_rate)).astype(float)
    # Apply the mask to the layer output and scale neurons that remain active 
    return layer_output * mask / (1 - dropout_rate)

In [19]:
import numpy as np

# Exemplu de strat cu 10 neuroni
layer_dropout = np.random.randn(5, 10)

# Rata de dropout de 20%
dropout_rate = 0.2

# Generarea măștii de dropout
# mask = np.random.rand(*layer_dropout.shape) < dropout_rate
layer_out= dropout_function(layer_dropout, dropout_rate)
# Aplicarea măștii de dropout
# layer_dropout *= mask

# print("Masca de dropout:", mask)
print("Stratul după aplicarea dropout-ului:", layer_out)

Stratul după aplicarea dropout-ului: [[ 0.6815675  -1.02524602  0.20943366 -0.11528553  0.31739028  0.08449674
   2.4366628  -0.         -0.34697865 -0.        ]
 [ 0.          0.13454623  0.24583093  0.97973427 -3.07694773 -0.727283
  -0.          0.92534061  1.31742973 -1.13707837]
 [-1.05934576 -0.          2.13619687 -0.         -0.          0.
  -1.46544022  0.          0.          4.04630197]
 [ 0.33282326  1.58236872 -0.35660268  0.0850678  -0.52563344  0.43458168
  -0.47505404  0.45178447 -0.         -1.12913946]
 [-0.06693346 -0.97980604  0.35177633  0.         -0.31121679  0.30353343
   0.42633837  2.49504948  1.40993373 -0.        ]]


In [62]:
A = np.array(
    [[1, 2, 3,8], [4, 5, 6,9], [7, 8, 9,1]]
)

permutation = np.random.permutation(A.shape[1])
print("perm: " , permutation)
print(A[0:10])
# print(A[B])

perm:  [2 1 0 3]
[[1 2 3 8]
 [4 5 6 9]
 [7 8 9 1]]
